// <auto-generated />
using System;
using AssetGuard_Project.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetGuard_Project.Migrations
{
    [DbContext(typeof(AssetGuardDbContext))]
    partial class AssetGuardDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AssetGuard_Project.Models.ActivosFijo", b =>
                {
                    b.Property<int>("IdAf")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdAF");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAf"), 1L, 1);

                    b.Property<int?>("DepartamentoAf")
                        .HasColumnType("int")
                        .HasColumnName("DepartamentoAF");

                    b.Property<decimal?>("DepreciacionAcumuladaAf")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DepreciacionAcumuladaAF");

                    b.Property<string>("DescripcionAf")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DescripcionAF");

                    b.Property<DateTime?>("FechaRegistroAf")
                        .HasColumnType("date")
                        .HasColumnName("FechaRegistroAF");

                    b.Property<int?>("TipoActivoAf")
                        .HasColumnType("int")
                        .HasColumnName("TipoActivoAF");

                    b.Property<decimal?>("ValorCompraAf")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ValorCompraAF");

                    b.HasKey("IdAf")
                        .HasName("PK__ActivosF__B773A0C2A38A4F45");

                    b.HasIndex("DepartamentoAf");

                    b.HasIndex("TipoActivoAf");

                    b.ToTable("ActivosFijos", (string)null);
                });

            modelBuilder.Entity("AssetGuard_Project.Models.CalculoDepreciacion", b =>
                {
                    b.Property<int>("IdCd")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCD");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCd"), 1L, 1);

                    b.Property<int?>("ActivoFijoCd")
                        .HasColumnType("int")
                        .HasColumnName("ActivoFijoCD");

                    b.Property<string>("AnoProcesoCd")
                        .HasMaxLength(4)
                        .IsUnicode(false)
                        .HasColumnType("varchar(4)")
                        .HasColumnName("AnoProcesoCD");

                    b.Property<int?>("CuentaCompra")
                        .HasColumnType("int");

                    b.Property<int?>("CuentaDepreciacion")
                        .HasColumnType("int");

                    b.Property<decimal?>("DepreciacionAcumuladaCd")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("DepreciacionAcumuladaCD");

                    b.Property<DateTime?>("FechaProcesoCd")
                        .HasColumnType("date")
                        .HasColumnName("FechaProcesoCD");

                    b.Property<string>("MesProcesoCd")
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("MesProcesoCD");

                    b.Property<decimal?>("MontoDepreciadoCd")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("MontoDepreciadoCD");

                    b.HasKey("IdCd")
                        .HasName("PK__CalculoD__B773908796FD6285");

                    b.HasIndex("ActivoFijoCd");

                    b.ToTable("CalculoDepreciacion", (string)null);
                });

            modelBuilder.Entity("AssetGuard_Project.Models.Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"), 1L, 1);

                    b.Property<string>("DescripcionDepartamento")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("EstadoDepartamento")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("IdDepartamento")
                        .HasName("PK__Departam__787A433DF01BE3B3");

                    b.ToTable("Departamentos", (string)null);
                });

            modelBuilder.Entity("AssetGuard_Project.Models.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"), 1L, 1);

                    b.Property<string>("CedulaEmpleado")
                        .HasMaxLength(11)
                        .IsUnicode(false)
                        .HasColumnType("varchar(11)");

                    b.Property<int?>("DepartamentoEmpleado")
                        .HasColumnType("int");

                    b.Property<string>("EstadoEmpleado")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.Property<DateTime?>("FechaIngresoEmpleado")
                        .HasColumnType("date");

                    b.Property<string>("NombreEmpleado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TipoPersonaEmpleado")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)");

                    b.HasKey("IdEmpleado")
                        .HasName("PK__Empleado__CE6D8B9E7C1BBA10");

                    b.HasIndex("DepartamentoEmpleado");

                    b.ToTable("Empleado", (string)null);
                });

            modelBuilder.Entity("AssetGuard_Project.Models.TiposActivo", b =>
                {
                    b.Property<int>("IdTa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdTA");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTa"), 1L, 1);

                    b.Property<int?>("CuentaContableCompraTa")
                        .HasColumnType("int")
                        .HasColumnName("CuentaContableCompraTA");

                    b.Property<int?>("CuentaContableDepreciacionTa")
                        .HasColumnType("int")
                        .HasColumnName("CuentaContableDepreciacionTA");

                    b.Property<string>("DescripcionTa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("DescripcionTA");

                    b.Property<string>("EstadoTa")
                        .HasMaxLength(8)
                        .IsUnicode(false)
                        .HasColumnType("varchar(8)")
                        .HasColumnName("EstadoTA");

                    b.HasKey("IdTa")
                        .HasName("PK__TiposAct__B7701AB7A654C049");

                    b.ToTable("TiposActivos", (string)null);
                });

            modelBuilder.Entity("AssetGuard_Project.Models.ActivosFijo", b =>
                {
                    b.HasOne("AssetGuard_Project.Models.Departamento", "DepartamentoAfNavigation")
                        .WithMany("ActivosFijos")
                        .HasForeignKey("DepartamentoAf")
                        .HasConstraintName("FK__ActivosFi__Depar__3E52440B");

                    b.HasOne("AssetGuard_Project.Models.TiposActivo", "TipoActivoAfNavigation")
                        .WithMany("ActivosFijos")
                        .HasForeignKey("TipoActivoAf")
                        .HasConstraintName("FK__ActivosFi__TipoA__3F466844");

                    b.Navigation("DepartamentoAfNavigation");

                    b.Navigation("TipoActivoAfNavigation");
                });

            modelBuilder.Entity("AssetGuard_Project.Models.CalculoDepreciacion", b =>
                {
                    b.HasOne("AssetGuard_Project.Models.ActivosFijo", "ActivoFijoCdNavigation")
                        .WithMany("CalculoDepreciacions")
                        .HasForeignKey("ActivoFijoCd")
                        .HasConstraintName("FK__CalculoDe__Activ__4222D4EF");

                    b.Navigation("ActivoFijoCdNavigation");
                });

            modelBuilder.Entity("AssetGuard_Project.Models.Empleado", b =>
                {
                    b.HasOne("AssetGuard_Project.Models.Departamento", "DepartamentoEmpleadoNavigation")
                        .WithMany("Empleados")
                        .HasForeignKey("DepartamentoEmpleado")
                        .HasConstraintName("FK__Empleado__Depart__3B75D760");

                    b.Navigation("DepartamentoEmpleadoNavigation");
                });

            modelBuilder.Entity("AssetGuard_Project.Models.ActivosFijo", b =>
                {
                    b.Navigation("CalculoDepreciacions");
                });

            modelBuilder.Entity("AssetGuard_Project.Models.Departamento", b =>
                {
                    b.Navigation("ActivosFijos");

                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("AssetGuard_Project.Models.TiposActivo", b =>
                {
                    b.Navigation("ActivosFijos");
                });
#pragma warning restore 612, 618
        }
    }
}
